#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate `thinkers_pinyin.py` -- the picker's pinyin search index.

    pip3 install --target /tmp/pylibs pypinyin
    PYTHONPATH=/tmp/pylibs python3 gen_pinyin.py

Run this whenever anyone is added to `thinkers_data.py`, or the new person will
be findable by Chinese and English name but not by pinyin. `test_thinkers.py`
fails if anyone with a Chinese name has no index entry, so a forgotten run is a
red test rather than a silent gap.

This is a BUILD-TIME tool and the only thing here that is not standard library.
The page gets the result as data (`thinkers_pinyin.py`), so the server itself
stays dependency-free -- the reason pypinyin is invoked through PYTHONPATH here
instead of being installed into the project.

Why pinyin at all: on a Chinese keyboard the reader types letters, so "kangde"
has to find 康德. Matching only the characters meant the picker worked for
Chinese names and for people you could already spell in English, and not for
the person you were actually looking for.

Three things get indexed per person, because all three are things people type:

  1. the primary reading, no tones, no spaces -- `kangde`
  2. the initials -- `kd`, the way a Chinese keyboard user abbreviates
  3. alternate readings of polyphonic characters -- `jiamiu` as well as
     `jiamou`, because pypinyin reads 缪 in 加缪 (Camus) as móu and a reader who
     knows the name types miù. Every alternate is a full string with one
     character swapped, not a cartesian product, so the list stays short:
     budgeted at 48 characters per person, primary and initials always kept.
"""
import io
import os
import sys

try:
    from pypinyin import pinyin, Style
except ImportError:  # pragma: no cover - a build tool, not shipped code
    sys.exit("需要 pypinyin：pip3 install --target /tmp/pylibs pypinyin\n"
             "然后 PYTHONPATH=/tmp/pylibs python3 gen_pinyin.py")

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from thinkers_data import RAW  # noqa: E402

BUDGET = 48          # characters of index per person, initials included
COMBO_CAP = 8        # alternate initial-strings kept when a name is ambiguous
OUT = os.path.join(HERE, "thinkers_pinyin.py")


def syllables(zh):
    """[[reading, ...], ...] -- one group of readings per character."""
    out = []
    for group in pinyin(zh, heteronym=True, style=Style.NORMAL, errors="ignore"):
        clean = [g.lower() for g in group if g and all(c.isalnum() for c in g)]
        if clean:
            out.append(clean)
    return out


def search_forms(zh, budget=BUDGET):
    """Everything about this name a reader might type, space-separated."""
    groups = syllables(zh)
    if not groups:
        return ""
    primary = [g[0] for g in groups]
    full = ["".join(primary)]
    for i, group in enumerate(groups):
        for alt in group[1:]:
            swapped = primary[:]
            swapped[i] = alt
            full.append("".join(swapped))
    combos = [""]
    for opts in [sorted(set(g[0] for g in group)) for group in groups]:
        combos = [c + o for c in combos for o in opts][:COMBO_CAP]
    # Primary and initials first: the budget below drops from the tail, and
    # those two are the ones that must never be the ones dropped.
    order = [full[0], combos[0]] + full[1:] + combos[1:]

    keep, used = [], 0
    for form in order:
        if not form or form in keep:
            continue
        if keep and used + len(form) + 1 > budget:
            continue
        keep.append(form)
        used += len(form) + 1
    return " ".join(keep)


def main():
    rows = [(slug, zh) for slug, zh, *_ in RAW]
    index = {slug: search_forms(zh) for slug, zh in rows}
    empty = [slug for slug, value in index.items() if not value]
    body = "".join('    "%s": "%s",\n' % (slug, index[slug]) for slug, _ in rows)
    io.open(OUT, "w", encoding="utf-8").write(
        '# -*- coding: utf-8 -*-\n'
        '"""GENERATED by gen_pinyin.py -- do not edit by hand.\n\n'
        "Pinyin search forms for the anchor picker, keyed by thinker id. See\n"
        "gen_pinyin.py for what is in each string and why.\n"
        '"""\n\n'
        "PY = {\n" + body + "}\n"
    )
    total = sum(len(v) for v in index.values())
    print("wrote %s: %d people, %d chars (mean %.1f), %d with no reading"
          % (os.path.basename(OUT), len(index), total, total / max(len(index), 1),
             len(empty)))
    if empty:
        print("  no reading (Latin/non-Han names, matched on the name itself):")
        print("   ", ", ".join(empty[:10]), "..." if len(empty) > 10 else "")


if __name__ == "__main__":
    main()
